const exams = [
 {id:"NEET",name:"NEET",desc:"Biology • Chemistry • Physics"},
 {id:"JEE",name:"JEE Main",desc:"Physics • Chemistry • Mathematics"},
 {id:"JEE_ADV",name:"JEE Advanced",desc:"Advanced PCM practice"},
 {id:"CDS",name:"CDS",desc:"English • GK • Maths"},
 {id:"NDA",name:"NDA",desc:"Maths • GAT"},
 {id:"UPSC",name:"UPSC CSE",desc:"GS • CSAT"},
 {id:"RAILWAY",name:"Railway",desc:"Maths • Reasoning • GK"},
 {id:"SSC",name:"SSC",desc:"Quant • Reasoning • English • GK"}
 {exam:"CDS",level:"Easy",q:"Who appoints the Governor of a state in India?",o:["Prime Minister","President","Chief Minister","Chief Justice"],a:1,e:"The Governor of a state is appointed by the President of India."},
 {exam:"CDS",level:"Easy",q:"Which is the largest planet in the Solar System?",o:["Earth","Saturn","Jupiter","Neptune"],a:2,e:"Jupiter is the largest planet in the Solar System."},
 {exam:"CDS",level:"Easy",q:"What is the capital of Rajasthan?",o:["Jodhpur","Jaipur","Udaipur","Kota"],a:1,e:"Jaipur is the capital of Rajasthan."},
 {exam:"CDS",level:"Easy",q:"Which gas is most abundant in Earth's atmosphere?",o:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"],a:2,e:"Nitrogen makes up about 78% of Earth's atmosphere."},
 {exam:"CDS",level:"Easy",q:"Who wrote the Indian national anthem?",o:["Bankim Chandra Chattopadhyay","Rabindranath Tagore","Sarojini Naidu","Subhas Chandra Bose"],a:1,e:"Rabindranath Tagore wrote 'Jana Gana Mana'."},
 {exam:"CDS",level:"Easy",q:"What is the currency of Japan?",o:["Won","Yuan","Yen","Ringgit"],a:2,e:"The currency of Japan is the Japanese Yen."},
 {exam:"CDS",level:"Easy",q:"Which vitamin is mainly produced in the skin through sunlight?",o:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"],a:3,e:"Sunlight helps the skin synthesize vitamin D."},
 {exam:"CDS",level:"Easy",q:"The headquarters of the United Nations is located in:",o:["Geneva","Paris","New York","London"],a:2,e:"The UN headquarters is in New York City."},
 {exam:"CDS",level:"Easy",q:"Which river is known as the 'Sorrow of Bihar'?",o:["Ganga","Kosi","Yamuna","Godavari"],a:1,e:"The Kosi River is traditionally known as the Sorrow of Bihar because of its floods."},
 {exam:"CDS",level:"Easy",q:"What is the SI unit of power?",o:["Joule","Newton","Watt","Pascal"],a:2,e:"Power is measured in watts (W)."},


 {exam:"CDS",level:"Medium",q:"Which Fundamental Right is guaranteed under Article 19?",o:["Right to Equality","Right to Freedom","Right against Exploitation","Right to Education"],a:1,e:"Article 19 guarantees several freedoms, including speech and expression."},
 {exam:"CDS",level:"Medium",q:"The Permanent Settlement was introduced by:",o:["Lord Wellesley","Lord Cornwallis","Lord Dalhousie","Lord Curzon"],a:1,e:"Lord Cornwallis introduced the Permanent Settlement in 1793."},
 {exam:"CDS",level:"Medium",q:"Which Indian state has the longest coastline?",o:["Tamil Nadu","Andhra Pradesh","Gujarat","Maharashtra"],a:2,e:"Gujarat has the longest coastline among Indian states."},
 {exam:"CDS",level:"Medium",q:"The Tropic of Cancer passes through how many Indian states?",o:["6","7","8","9"],a:2,e:"The Tropic of Cancer passes through 8 Indian states."},
 {exam:"CDS",level:"Medium",q:"Which blood group is commonly called the universal donor for red blood cells?",o:["AB+","O−","A+","B−"],a:1,e:"O-negative red blood cells are generally considered the universal donor type."},
 {exam:"CDS",level:"Medium",q:"The Green Revolution in India was mainly associated with increased production of:",o:["Tea","Wheat and rice","Cotton","Sugarcane"],a:1,e:"The Green Revolution greatly increased wheat and rice production."},
 {exam:"CDS",level:"Medium",q:"Which Constitutional Amendment reduced the voting age from 21 to 18?",o:["42nd","44th","61st","73rd"],a:2,e:"The 61st Constitutional Amendment Act, 1988, 